run:
    timeout: 3m
    tests: true

linters-settings:
    exhaustive:
      default-signifies-exhaustive: false
    golint:
      min-confidence: 0

linters:
    disable-all: true
    enable:
    - dogsled
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
