run:
    timeout: 3m
    tests: true

linters-settings:
    exhaustive:
      default-signifies-exhaustive: false
    golint:
      min-confidence: 0
    depguard:
      rules:
        main:
          files:
          - $all
          - "!$test"
          allow:
          - $gostd
          - github.com/splunk/qbec
          - github.com/spf13/cobra

linters:
    disable-all: true
    enable:
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - varcheck
