before:
  hooks:
    - make release-notes
builds:
  - id: qbec
    binary: qbec
    main: ./
    ldflags:
      - -X github.com/splunk/qbec/internal/commands.version={{.Version}} -X github.com/splunk/qbec/internal/commands.commit={{.Commit}} -X github.com/splunk/qbec/internal/commands.goVersion={{.Env.GO_VERSION}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
  - id: jsonnet-qbec
    binary: jsonnet-qbec
    main: cmd/jsonnet-qbec/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: qbec
    tap:
      owner: splunk
      name: homebrew-tap
    url_template: https://rogii-sre-dist-pub.s3.amazonaws.com/qbec/{{.ArtifactName}}
    homepage: "https://qbec.io/"
    description: Qbec (pronounced like the Canadian province) is a CLI tool that allows you to create Kubernetes objects on multiple Kubernetes clusters or namespaces configured correctly for the target environment in question.

    test: |
      system "#{bin}/qbec version"

    install: |
      bin.install ["qbec", "jsonnet-qbec"]

checksum:
  name_template: "sha256-checksums.txt"
snapshot:
  name_template: "{{.Version}}-rogii"
changelog:
  sort: asc
  filters:
    exclude:
      - "README.md"
      - ".gitignore"
      - "^site:"
      - "^examples:"
      - Merge pull request
      - Merge branch
