language: go
sudo: false
go:
  - 1.10.x

before_install:
  - go get github.com/mattn/goveralls

install:
  make install-ci install get

script:
  - make
  - make clean
  - diff -u <(echo -n) <(gofmt -d .)
