[[constraint]]
    name = "github.com/emicklei/go-restful" # MIT license
    version = "v1.2"

[[constraint]]
  name = "github.com/ghodss/yaml" # MIT license
  version = "1.0.0"

[[constraint]]
    name = "github.com/go-openapi/spec" # Apache 2.0 license
    version = "v0.18.0"

[[constraint]]
    name = "github.com/go-openapi/strfmt" # Apache 2.0 license
    version = "v0.18.0"

[[constraint]]
    name = "github.com/go-openapi/validate" # # Apache 2.0 license
    version = "v0.18.0"

[[constraint]]
  name = "github.com/google/go-jsonnet" # Apache 2.0 license
  version = "0.13.0"

[[constraint]]
    name = "github.com/googleapis/gnostic" # Apache 2.0 license
    version = "v0.2.0"

[[constraint]]
    name = "github.com/jonboulle/clockwork" # Apache 2.0 license
    version = "v0.1.0"

[[constraint]]
    name = "github.com/mattn/go-isatty" # MIT license
    version = "v0.0.4"

[[constraint]]
  name = "github.com/pkg/errors" # BSD 2-Clause "Simplified" License
  version = "0.8.0"

[[constraint]]
    name = "github.com/pmezard/go-difflib" # unclear license, see: https://github.com/pmezard/go-difflib/blob/master/LICENSE
    version = "v1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra" # Apache 2.0 license
  version = "0.0.3"

[[constraint]]
  name = "k8s.io/apimachinery" # Apache 2.0 license
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "k8s.io/client-go" # Apache 2.0 license
  version = "v7.0.0"

[[constraint]]
    name = "k8s.io/kube-openapi" # Apache 2.0 license
    revision = "0317810137be915b9cf888946c6e115c1bfac693"

[[constraint]]
    name = "k8s.io/kubernetes" # Apache 2.0 license
    version = "v1.13.3"

[[constraint]]
    name = "github.com/chzyer/readline" # MIT license
    version = "v1.4"

[[override]]
    name = "github.com/golang/protobuf"
    version = "v1.3.1"

[[override]]
    name = "github.com/Azure/go-autorest"
    revision = "d4e6b95c12a08b4de2d48b45d5b4d594e5d32fab"

[prune]
  go-tests = true
  unused-packages = true
