# Copyright 2025 Splunk Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: example1
spec:
  # componentsDir: components
  # paramsFile: params.libsonnet
  postProcessor: pp.jsonnet
  libPaths:
    - lib
  excludes:
    - service2
  baseProperties:
    core: no-override
    envType: unknown
    extra:
      foo: bar
      bar: baz
  vars:
    topLevel:
      - name: tlaFoo
        components: ['service2']
    external:
      - name: externalFoo
        default: 'bar'
    computed:
      - name: c1
        code: |
          {
            env: std.extVar('qbec.io/env'),
          }
      - name: c2
        code: |
          {
            vars: std.extVar('c1'),
          }
      - name: c3
        code: |
          import 'compute.jsonnet'
  environments:
    local:
      context: minikube
      properties:
        envType: local
    dev:
      server: https://dev-server
      includes:
        - service2
      excludes:
        - service1
      properties:
        envType: development
        extra:
          foo: baz
          bar: null
  envFiles:
    - '*-env.yaml'
