---
apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: example1
spec:
  # componentsDir: components
  # paramsFile: params.libsonnet
  preProcessor: pre-proc.libsonnet
  postProcessor: pp.jsonnet
  libPaths:
  - lib
  excludes:
  - service2
  baseProperties:
    core: no-override
    envType: unknown
    extra:
      foo: bar
      bar: baz
  vars:
    topLevel:
      - name: tlaFoo
        components: [ 'service2' ]
    external:
      - name: externalFoo
        default: 'bar'
    computed:
      - name: c1
        code: |
          {
            env: std.extVar('qbec.io/env'),
          }
      - name: c2
        code: |
          {
            vars: std.extVar('c1'),
          }
      - name: c3
        code: |
          import 'compute.jsonnet'
  environments:
    local:
      context: minikube
      properties:
        envType: local
    dev:
      server: https://dev-server
      includes:
      - service2
      excludes:
      - service1
      properties:
        envType: development
        extra:
          foo: baz
          bar: null
  envFiles: 
  - prod-env.yaml
  - stage-env.yaml

