---
apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: example1
spec:
  # componentsDir: components
  # paramsFile: params.libsonnet
  postProcessor: pp.jsonnet
  libPaths:
  - lib
  excludes:
  - service2
  vars:
    topLevel:
      - name: tlaFoo
        components: [ 'service2' ]
    external:
      - name: externalFoo
        default: 'bar'
  environments:
    dev:
      server: https://dev-server
      includes:
      - service2
      excludes:
      - service1
    prod:
      server: https://prod-server
      includes:
      - service2
