apiVersion: batch/v1
kind: Job
metadata:
  generateName: tj-
spec:
  template:
    spec:
      containers:
        - name: pi
          image: perl
          command: ["perl"]
          args: ["-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
